//init
$("#aboutPage").show()
$("#projectPage").hide()
$("#contactPage").hide()

$("#homeAbout").click(function(){
    $("#aboutPage").show()
    $("#homeAbout").addClass("active")
    $("#projectPage").hide()
    $("#homeProject").removeClass("active")
    $("#contactPage").hide()
    $("#homeSkills").removeClass("active")
})
$("#homeProject").click(function(){
    $("#projectPage").show()
    $("#homeProject").addClass("active")
    $("#aboutPage").hide()
    $("#homeAbout").removeClass("active")
    $("#contactPage").hide()
    $("#homeSkills").removeClass("active")
})
$("#homeSkills").click(function(){
    $("#contactPage").show()
    $("#homeSkills").addClass("active")
    $("#projectPage").hide()
    $("#homeProject").removeClass("active")
    $("#aboutPage").hide()
    $("#homeAbout").removeClass("active")
})
